"""init schema

Revision ID: 07aa1113d06a
Revises: 
Create Date: 2026-08-21 14:52:41.691871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07aa1113d06a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_bindings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("provider <> ''", name='oauth_provider_nonempty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_bindings_user_id'), 'oauth_bindings', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fridges',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name='fridge_status_chk'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridges_owner_id'), 'fridges', ['owner_id'], unique=False)
    op.create_table('recipes',
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=16), server_default='easy', nullable=False),
    sa.Column('meat_type', sa.String(length=16), server_default='mixed', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='private', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy','medium','hard')", name='recipe_difficulty_chk'),
    sa.CheckConstraint("meat_type IN ('meat','veg','mixed')", name='recipe_meat_type_chk'),
    sa.CheckConstraint("status IN ('private','pending','approved','rejected')", name='recipe_status_chk'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_author_id'), 'recipes', ['author_id'], unique=False)
    op.create_table('case_files',
    sa.Column('fridge_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('cooked_at', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 1 AND 5)', name='casefile_rating_chk'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_files_fridge_id'), 'case_files', ['fridge_id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('fridge_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("type IN ('registration','fridge')", name='invite_type_chk'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=False)
    op.create_index(op.f('ix_invite_codes_fridge_id'), 'invite_codes', ['fridge_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fridge_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("role IN ('owner','member')", name='membership_role_chk'),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_fridge_id'), 'memberships', ['fridge_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('recipe_ingredient_lines',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.String(length=64), server_default='', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='main', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("role IN ('main','seasoning')", name='recipe_line_role_chk'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredient_lines_recipe_id'), 'recipe_ingredient_lines', ['recipe_id'], unique=False)
    op.create_table('stock_items',
    sa.Column('fridge_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.String(length=64), server_default='', nullable=False),
    sa.Column('zone', sa.String(length=16), server_default='fridge', nullable=False),
    sa.Column('state', sa.String(length=16), server_default='raw', nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('raw','cooked','leftover')", name='stock_state_chk'),
    sa.CheckConstraint("zone IN ('freezer','fridge','pantry')", name='stock_zone_chk'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_fridge_id'), 'stock_items', ['fridge_id'], unique=False)
    op.create_table('case_file_entries',
    sa.Column('casefile_id', sa.BigInteger(), nullable=False),
    sa.Column('stockitem_name', sa.String(length=128), nullable=False),
    sa.Column('quantity_used', sa.String(length=64), server_default='', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['casefile_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_file_entries_casefile_id'), 'case_file_entries', ['casefile_id'], unique=False)
    op.create_table('fridge_events',
    sa.Column('fridge_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('stockitem_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("action IN ('created','updated','deleted','consumed','discarded')", name='fridge_event_action_chk'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridges.id'], ),
    sa.ForeignKeyConstraint(['stockitem_id'], ['stock_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_events_fridge_id'), 'fridge_events', ['fridge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fridge_events_fridge_id'), table_name='fridge_events')
    op.drop_table('fridge_events')
    op.drop_index(op.f('ix_case_file_entries_casefile_id'), table_name='case_file_entries')
    op.drop_table('case_file_entries')
    op.drop_index(op.f('ix_stock_items_fridge_id'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_recipe_ingredient_lines_recipe_id'), table_name='recipe_ingredient_lines')
    op.drop_table('recipe_ingredient_lines')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_fridge_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invite_codes_fridge_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_case_files_fridge_id'), table_name='case_files')
    op.drop_table('case_files')
    op.drop_index(op.f('ix_recipes_author_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_fridges_owner_id'), table_name='fridges')
    op.drop_table('fridges')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_bindings_user_id'), table_name='oauth_bindings')
    op.drop_table('oauth_bindings')
    # ### end Alembic commands ###
